#!/bin/sh

NEW_UUID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
echo "/tmp/$NEW_UUID"
export BEAKER_USER_DATA_PATH="/tmp/$NEW_UUID"
/usr/local/bin/beaker
# BEAKER_USER_DATA_PATH="/tmp/$NEW_UUID" && /usr/local/bin/beaker
